POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzYzU0OGJlYzZlMmM3YjJmNjQyNjk2MiIsImlhdCI6MTY3Mzg3MzYwOSwiZXhwIjoxNjc0MDQ2NDA5fQ.SqTPnqRI0fD9oERS2sjM8r8PYMmEpzxmuf_LGvYES6k

{
  "title": "My Book",
  "author": "hexd",
  "url": "some url",
  "likes": 1
}
